### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tomdev10** [tomdev10/ibm-bluepages-js#18]
As the new owner of the repo, I wanted to start thinking about some changes that could be made to improve this repo further. A couple of ideas at this stage:

- Remove dependancy on Python
- Utilise ES6 modules for import/export rather than `require`

I will add to this thread as more ideas emerge, but welcome any other thoughts. 

Aiming to close this by 31/01/22 and create a more explicit set of issues

**Comment by tomdev10** [comment]
Rough idea of tasks:
- [ ] Convert to ES Modules 
- [ ] Understand why "bundlephobia" fails
- [ ] Build CI/CD pipeline using GitHub actions, to test and publish
- [ ] Manage size of dependencies
- [ ] Add further methods from experimental API
